sudo: false
env: RELEASE_TESTING=1
language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.21"
# MooX::ClassAttribute missing from yanick's d2p2 deps
# temp use of yanicks repo for d2p2
install:
  - cpanm --quiet --notest MooX::ClassAttribute
  - cpanm --quiet --notest Dancer https://github.com/yanick/Dancer2/tree/plugins-yanick Test::CheckManifest Test::Spelling Pod::Coverage Test::Pod::Coverage
  - cpanm --quiet --installdeps --notest .
