sudo: false
env: RELEASE_TESTING=1
language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.21"
# MooX::ClassAttribute missing from yanick's d2p2 deps
# temp use of yanicks repo for d2p2
before_install:
  - cpanm --quiet --notest MooX::ClassAttribute Test::WWW::Mechanize::PSGI Test::CPAN::Meta
  - cpanm --quiet --notest Dist::Zilla
  - git clone git://github.com/yanick/Dancer2.git ~/yanick-d2
  - cd ~/yanick-d2
  - git checkout plugins-yanick
  - dzil authordeps --missing | cpanm --quiet --notest
  - dzil listdeps --missing | cpanm --quiet --notest
  - dzil build --in d2build
  - cd d2build
  - cpanm --quiet --installdeps --notest .
  - perl Makefile.PL
  - make install
  - cd ~
install:
  - cpanm --quiet --notest Dancer Test::CheckManifest Test::Spelling Pod::Coverage Test::Pod::Coverage
  - cpanm --quiet --installdeps --notest .
